### PR TITLE
Remove myself as a core team member

### PR DESCRIPTION
**Pull request by hdgarrood**
See https://harry.garrood.me/blog/stepping-down-from-purescript/

### CODE REVIEW

**Review by garyb — APPROVED** [review]
Sad approve

**Comment by thomashoneyman** [comment]
Also a sad approve from me. Also, what do you think of adding an “alumni” section that lists previous core team members, as a way to honor their work? Then you could be listed there along with Phil and others.

**Review by thomashoneyman — APPROVED** [review]

**Comment by garyb** [comment]
> what do you think of adding an “alumni” section that lists previous core team members, as a way to honor their work? Then you could be listed there along with Phil and others.

I like the sound of that!

**Comment by hdgarrood** [comment]
An alumni section sounds reasonable to me, although speaking personally I don't feel that there's too much of a need for it - I feel like my work is sufficiently honoured already :) I think I'll just merge this for now, and we can add an alumni section in a separate PR if we want.

**Pull request merged**
